#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main7.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000006872.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006873.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006874.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006875.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006880.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006881.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006882.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006883.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006884.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006885.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006886.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006888.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006889.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006891.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006892.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006894.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006895.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006897.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006898.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006900.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006901.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006903.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006904.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006906.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006907.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006909.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006910.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006912.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006913.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006915.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006916.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006918.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006919.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006921.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006922.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006923.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006924.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006925.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006930.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006931.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006932.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006933.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006934.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006935.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006936.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006938.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006939.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006941.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006942.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006944.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006945.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006947.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006948.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006950.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006951.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006953.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006954.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006956.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006957.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006959.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006960.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006962.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006963.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006965.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006966.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006968.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006969.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006971.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006972.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006974.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006975.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006977.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006978.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006980.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006981.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006983.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006984.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006985.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006986.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006987.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006992.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006993.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006994.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006995.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006996.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006999.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007000.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007003.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007004.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007007.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007008.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007011.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007012.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007015.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007016.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007019.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007020.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007023.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007024.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007027.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007028.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007031.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007032.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007035.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007036.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007039.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007040.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007041.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007042.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007043.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007044.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007045.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007046.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007047.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007050.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007051.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007052.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007053.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007056.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007057.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007058.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007059.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007060.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007061.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007062.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007065.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007066.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007069.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007070.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007071.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007072.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007073.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007076.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007077.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007078.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007079.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007082.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007083.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007084.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007085.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007086.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007087.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007088.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007089.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007090.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007092.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007093.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007095.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007096.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007098.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007099.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007101.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007102.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007103.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007104.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007105.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007106.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007107.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007108.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007110.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007111.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007113.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007114.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007116.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007117.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007119.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007120.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007123.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007124.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007127.inp --no-xml-output
date

rm -rf $TMPDIR
