#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main3.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000005836.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005837.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005838.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005839.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005842.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005843.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005844.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005845.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005848.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005849.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005850.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005851.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005852.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005853.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005854.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005855.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005856.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005858.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005859.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005861.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005862.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005864.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005865.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005867.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005868.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005869.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005870.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005871.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005872.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005873.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005874.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005875.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005876.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005877.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005878.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005879.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005880.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005881.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005882.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005883.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005884.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005885.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005886.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005887.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005888.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005889.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005890.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005891.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005892.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005894.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005895.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005897.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005898.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005900.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005901.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005903.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005904.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005905.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005906.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005907.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005908.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005909.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005910.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005911.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005912.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005913.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005914.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005915.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005916.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005917.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005918.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005919.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005920.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005921.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005922.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005923.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005924.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005925.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005926.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005927.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005928.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005929.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005930.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005931.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005932.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005933.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005934.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005935.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005936.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005937.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005938.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005939.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005940.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005941.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005942.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005943.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005944.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005946.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005947.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005949.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005950.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005952.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005953.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005955.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005956.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005957.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005958.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005959.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005960.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005961.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005962.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005964.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005965.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005967.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005968.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005970.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005971.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005973.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005974.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005976.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005977.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005979.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005980.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005982.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005983.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005985.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005986.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005988.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005989.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005991.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005992.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005994.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005995.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005997.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005998.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006001.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006002.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006005.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006006.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006007.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006008.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006009.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006013.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006014.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006015.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006016.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006017.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006018.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006019.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006020.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006021.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006022.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006027.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006028.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006029.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006030.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006031.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006032.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006033.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006035.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006036.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006038.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006039.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006041.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006042.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006044.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006045.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006046.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006047.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006048.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006053.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006054.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006055.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006056.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006057.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006058.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006059.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006061.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006062.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006064.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006065.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006067.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006068.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006070.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006071.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006073.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006074.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006076.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006077.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006079.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006080.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006082.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006083.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006084.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006085.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006086.inp --no-xml-output
date

rm -rf $TMPDIR
