#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main12.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000008185.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008186.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008187.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008188.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008189.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008190.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008191.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008192.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008193.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008194.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008195.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008196.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008197.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008198.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008199.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008200.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008201.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008202.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008203.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008204.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008205.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008206.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008207.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008208.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008209.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008211.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008212.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008214.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008215.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008217.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008218.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008220.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008221.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008222.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008223.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008224.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008225.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008226.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008227.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008229.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008230.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008232.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008233.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008235.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008236.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008238.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008239.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008241.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008242.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008244.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008245.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008247.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008248.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008250.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008251.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008254.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008255.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008258.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008259.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008260.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008261.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008262.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008263.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008264.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008265.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008266.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008267.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008268.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008269.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008270.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008271.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008273.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008274.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008276.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008277.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008279.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008280.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008282.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008283.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008284.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008285.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008286.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008287.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008288.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008289.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008290.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008291.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008292.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008293.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008294.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008295.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008296.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008297.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008298.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008299.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008300.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008301.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008302.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008303.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008304.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008305.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008306.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008307.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008309.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008310.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008312.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008313.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008315.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008316.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008318.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008319.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008320.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008321.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008322.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008323.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008324.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008325.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008326.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008327.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008328.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008329.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008330.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008331.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008332.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008333.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008334.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008335.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008336.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008337.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008338.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008339.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008340.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008341.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008342.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008343.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008344.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008345.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008346.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008347.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008348.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008349.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008350.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008351.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008352.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008353.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008354.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008355.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008356.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008357.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008358.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008359.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008361.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008362.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008364.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008365.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008367.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008368.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008370.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008371.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008372.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008373.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008374.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008375.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008376.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008377.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008379.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008380.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008382.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008383.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008385.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008386.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008388.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008389.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008391.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008392.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008394.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008395.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008397.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008398.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008400.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008401.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008403.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008404.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008406.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008407.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008409.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008410.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008412.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008413.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008416.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008417.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008420.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008421.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008422.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008423.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008424.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008425.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008426.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008427.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008428.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008429.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008430.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008431.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008432.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008433.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008435.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008436.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008438.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008439.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008441.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008442.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008444.inp --no-xml-output
date

rm -rf $TMPDIR
