#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main25.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000011577.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011579.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011580.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011582.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011583.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011585.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011586.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011588.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011589.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011590.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011591.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011592.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011593.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011594.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011595.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011596.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011597.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011598.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011599.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011600.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011601.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011602.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011603.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011604.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011605.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011606.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011607.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011608.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011609.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011610.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011611.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011612.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011613.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011614.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011615.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011616.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011617.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011618.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011619.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011620.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011621.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011622.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011623.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011624.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011625.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011626.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011627.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011628.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011629.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011630.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011631.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011632.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011633.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011634.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011635.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011636.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011637.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011638.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011639.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011640.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011641.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011642.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011643.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011644.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011645.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011646.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011647.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011648.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011649.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011650.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011651.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011652.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011653.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011654.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011655.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011656.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011657.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011658.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011659.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011660.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011661.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011662.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011663.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011664.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011665.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011666.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011667.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011668.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011669.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011670.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011671.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011672.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011673.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011674.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011675.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011676.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011677.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011678.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011679.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011680.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011681.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011682.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011683.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011684.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011685.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011686.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011687.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011688.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011689.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011690.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011691.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011692.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011693.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011695.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011696.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011698.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011699.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011701.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011702.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011704.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011705.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011706.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011707.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011708.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011709.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011710.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011711.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011713.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011714.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011716.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011717.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011719.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011720.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011722.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011723.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011725.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011726.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011728.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011729.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011731.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011732.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011734.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011735.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011737.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011738.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011740.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011741.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011743.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011744.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011746.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011747.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011749.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011750.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011752.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011753.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011755.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011756.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011758.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011759.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011761.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011762.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011764.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011765.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011767.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011768.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011770.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011771.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011773.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011774.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011776.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011777.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011779.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011780.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011782.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011783.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011785.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011786.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011788.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011789.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011791.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011792.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011794.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011795.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011798.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011799.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011802.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011803.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011804.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011805.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011806.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011807.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011808.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011809.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011810.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011811.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011812.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011813.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011814.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011819.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011820.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011821.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011822.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011823.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011824.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011825.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011827.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011828.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011830.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011831.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011833.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011834.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011836.inp --no-xml-output
date

rm -rf $TMPDIR
