#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main11.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000007914.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007916.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007917.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007919.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007920.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007922.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007923.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007925.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007926.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007927.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007928.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007929.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007930.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007931.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007932.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007934.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007935.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007937.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007938.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007940.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007941.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007943.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007944.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007946.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007947.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007949.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007950.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007952.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007953.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007955.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007956.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007958.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007959.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007961.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007962.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007964.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007965.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007967.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007968.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007970.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007971.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007973.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007974.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007976.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007977.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007979.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007980.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007982.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007983.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007985.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007986.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007988.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007989.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007991.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007992.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007995.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007996.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007999.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008000.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008001.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008002.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008003.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008007.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008008.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008009.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008010.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008011.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008012.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008013.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008014.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008015.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008016.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008021.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008022.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008023.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008024.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008025.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008026.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008027.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008029.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008030.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008032.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008033.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008035.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008036.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008038.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008039.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008040.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008041.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008042.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008047.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008048.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008049.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008050.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008051.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008052.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008053.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008055.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008056.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008058.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008059.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008061.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008062.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008064.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008065.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008067.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008068.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008070.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008071.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008073.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008074.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008076.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008077.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008078.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008079.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008080.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008085.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008086.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008087.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008088.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008089.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008090.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008091.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008093.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008094.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008096.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008097.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008099.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008100.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008102.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008103.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008105.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008106.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008108.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008109.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008111.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008112.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008114.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008115.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008117.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008118.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008120.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008121.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008123.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008124.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008126.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008127.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008128.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008129.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008130.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008135.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008136.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008137.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008138.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008139.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008140.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008141.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008143.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008144.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008146.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008147.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008149.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008150.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008152.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008153.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008155.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008156.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008158.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008159.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008161.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008162.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008164.inp --no-xml-output
date

rm -rf $TMPDIR
