#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main39.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000015229.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015231.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015232.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015234.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015235.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015237.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015238.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015240.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015241.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015242.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015243.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015244.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015249.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015250.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015251.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015252.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015253.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015254.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015255.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015257.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015258.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015260.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015261.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015263.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015264.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015266.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015267.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015269.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015270.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015272.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015273.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015275.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015276.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015278.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015279.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015281.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015282.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015284.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015285.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015287.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015288.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015290.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015291.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015293.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015294.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015296.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015297.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015299.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015300.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015302.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015303.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015305.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015306.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015308.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015309.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015311.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015312.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015314.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015315.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015317.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015318.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015320.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015321.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015323.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015324.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015326.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015327.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015328.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015329.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015330.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015335.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015336.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015337.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015338.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015339.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015340.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015341.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015343.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015344.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015346.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015347.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015349.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015350.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015352.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015353.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015355.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015356.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015358.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015359.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015361.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015362.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015364.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015365.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015367.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015368.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015370.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015371.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015373.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015374.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015376.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015377.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015379.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015380.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015382.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015383.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015385.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015386.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015388.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015389.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015391.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015392.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015394.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015395.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015397.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015398.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015400.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015401.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015403.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015404.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015406.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015407.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015409.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015410.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015412.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015413.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015415.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015416.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015418.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015419.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015421.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015422.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015424.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015425.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015426.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015427.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015428.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015433.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015434.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015435.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015436.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015437.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015438.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015439.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015441.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015442.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015444.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015445.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015447.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015448.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015450.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015451.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015453.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015454.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015456.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015457.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015459.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015460.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015462.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015463.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015465.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015466.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015468.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015469.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015471.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015472.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015474.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015475.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015477.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015478.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015480.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015481.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015483.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015484.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015486.inp --no-xml-output
date

rm -rf $TMPDIR
