#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main58.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000020209.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020211.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020212.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020214.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020215.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020217.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020218.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020220.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020221.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020223.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020224.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020226.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020227.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020229.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020230.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020232.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020233.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020235.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020236.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020238.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020239.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020241.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020242.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020244.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020245.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020247.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020248.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020250.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020251.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020253.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020254.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020256.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020257.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020258.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020259.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020260.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020265.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020266.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020267.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020268.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020269.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020270.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020271.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020273.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020274.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020276.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020277.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020279.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020280.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020282.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020283.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020285.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020286.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020288.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020289.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020291.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020292.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020294.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020295.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020297.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020298.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020300.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020301.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020303.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020304.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020306.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020307.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020309.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020310.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020312.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020313.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020315.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020316.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020318.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020319.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020321.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020322.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020324.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020325.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020327.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020328.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020330.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020331.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020333.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020334.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020336.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020337.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020339.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020340.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020342.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020343.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020345.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020346.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020348.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020349.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020351.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020352.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020354.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020355.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020357.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020358.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020360.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020361.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020363.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020364.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020366.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020367.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020369.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020370.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020372.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020373.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020375.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020376.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020378.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020379.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020380.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020381.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020382.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020387.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020388.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020389.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020390.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020391.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020394.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020395.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020398.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020399.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020402.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020403.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020406.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020407.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020410.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020411.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020414.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020415.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020418.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020419.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020422.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020423.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020426.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020427.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020430.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020431.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020434.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020435.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020438.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020439.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020442.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020443.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020446.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020447.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020450.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020451.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020454.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020455.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020458.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020459.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020462.inp --no-xml-output
date

rm -rf $TMPDIR
