#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main42.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000016000.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016003.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016004.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016007.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016008.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016011.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016012.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016015.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016016.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016019.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016020.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016023.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016024.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016027.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016028.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016031.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016032.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016035.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016036.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016039.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016040.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016043.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016044.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016047.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016048.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016051.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016052.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016055.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016056.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016059.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016060.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016063.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016064.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016067.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016068.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016071.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016072.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016075.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016076.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016077.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016078.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016079.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016080.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016081.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016082.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016083.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016086.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016087.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016088.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016089.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016092.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016093.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016094.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016095.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016096.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016097.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016098.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016101.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016102.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016105.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016106.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016107.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016108.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016109.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016112.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016113.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016114.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016115.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016118.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016119.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016120.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016121.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016122.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016123.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016124.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016125.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016126.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016128.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016129.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016131.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016132.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016134.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016135.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016137.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016138.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016139.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016140.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016141.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016142.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016143.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016144.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016146.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016147.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016149.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016150.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016152.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016153.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016155.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016156.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016159.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016160.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016163.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016164.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016165.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016166.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016167.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016170.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016171.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016172.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016173.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016176.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016177.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016178.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016179.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016180.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016181.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016182.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016183.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016184.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016186.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016187.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016189.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016190.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016192.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016193.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016195.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016196.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016197.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016198.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016199.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016200.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016201.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016202.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016203.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016204.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016205.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016206.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016207.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016208.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016209.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016210.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016211.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016212.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016213.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016214.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016215.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016216.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016217.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016218.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016219.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016220.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016222.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016223.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016225.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016226.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016228.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016229.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016231.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016232.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016233.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016234.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016235.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016236.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016237.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016238.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016240.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016241.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016243.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016244.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016246.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016247.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016249.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016250.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016252.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016253.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016255.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016256.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016258.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016259.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000016261.inp --no-xml-output
date

rm -rf $TMPDIR
