#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main39.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000015229.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015230.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015231.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015232.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015233.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015234.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015235.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015236.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015237.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015238.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015239.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015240.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015241.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015242.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015243.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015244.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015245.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015246.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015247.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015248.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015249.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015250.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015251.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015252.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015253.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015254.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015255.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015256.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015257.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015258.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015259.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015260.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015261.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015262.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015263.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015264.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015265.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015266.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015267.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015268.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015269.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015270.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015271.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015272.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015273.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015274.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015275.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015276.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015277.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015278.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015279.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015280.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015281.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015282.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015283.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015284.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015285.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015286.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015287.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015288.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015289.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015290.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015291.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015292.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015293.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015294.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015295.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015296.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015297.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015298.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015299.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015300.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015301.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015302.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015303.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015304.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015305.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015306.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015307.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015308.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015309.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015311.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015312.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015314.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015315.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015317.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015318.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015320.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015321.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015322.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015323.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015324.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015325.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015326.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015327.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015329.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015330.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015332.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015333.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015335.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015336.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015338.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015339.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015341.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015342.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015344.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015345.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015347.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015348.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015350.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015351.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015353.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015354.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015356.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015357.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015359.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015360.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015362.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015363.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015365.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015366.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015368.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015369.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015371.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015372.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015374.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015375.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015377.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015378.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015380.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015381.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015383.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015384.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015386.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015387.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015389.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015390.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015392.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015393.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015395.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015396.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015398.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015399.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015401.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015402.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015404.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015405.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015407.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015408.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015410.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015411.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015413.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015414.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015416.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015417.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015419.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015420.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015422.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015423.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015426.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015427.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015430.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015431.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015432.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015433.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015434.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015438.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015439.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015440.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015441.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015442.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015443.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015444.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015445.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015446.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015447.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015452.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015453.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015454.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015455.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015456.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015457.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015458.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015460.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015461.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015463.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015464.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015466.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015467.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015469.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015470.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015471.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015472.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015473.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015478.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015479.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015480.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015481.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015482.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015483.inp --no-xml-output
date

rm -rf $TMPDIR
