#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main19.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000010001.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010003.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010004.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010006.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010007.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010009.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010010.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010012.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010013.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010015.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010016.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010018.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010019.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010021.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010022.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010024.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010025.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010028.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010029.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010032.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010033.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010034.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010035.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010036.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010037.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010038.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010039.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010040.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010041.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010042.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010043.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010044.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010045.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010047.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010048.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010050.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010051.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010053.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010054.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010056.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010057.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010058.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010059.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010060.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010061.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010062.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010063.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010064.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010065.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010066.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010067.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010068.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010069.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010070.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010071.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010072.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010073.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010074.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010075.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010076.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010077.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010078.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010079.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010080.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010081.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010083.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010084.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010086.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010087.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010089.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010090.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010092.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010093.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010094.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010095.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010096.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010097.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010098.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010099.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010100.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010101.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010102.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010103.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010104.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010105.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010106.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010107.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010108.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010109.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010110.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010111.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010112.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010113.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010114.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010115.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010116.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010117.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010118.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010119.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010120.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010121.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010122.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010123.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010124.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010125.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010126.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010127.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010128.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010129.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010130.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010131.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010132.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010133.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010135.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010136.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010138.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010139.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010141.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010142.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010144.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010145.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010146.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010147.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010148.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010149.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010150.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010151.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010153.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010154.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010156.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010157.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010159.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010160.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010162.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010163.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010165.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010166.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010168.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010169.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010171.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010172.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010174.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010175.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010177.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010178.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010180.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010181.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010183.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010184.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010186.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010187.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010190.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010191.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010194.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010195.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010196.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010197.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010198.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010199.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010200.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010201.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010202.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010203.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010204.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010205.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010206.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010207.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010209.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010210.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010212.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010213.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010215.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010216.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010218.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010219.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010220.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010221.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010222.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010223.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010224.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010225.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010226.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010227.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010228.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010229.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010230.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010231.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010232.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010233.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010234.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010235.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010236.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010237.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010238.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010239.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010240.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010241.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010242.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010243.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010245.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010246.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010248.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010249.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010251.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010252.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010254.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010255.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010256.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010257.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010258.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010259.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010260.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010261.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010262.inp --no-xml-output
date

rm -rf $TMPDIR
