#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main0.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000005083.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005084.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005085.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005086.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005087.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005088.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005089.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005092.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005093.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005094.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005095.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005096.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005097.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005098.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005099.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005100.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005101.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005102.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005103.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005106.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005107.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005110.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005111.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005112.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005113.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005114.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005115.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005116.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005117.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005118.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005119.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005120.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005121.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005122.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005127.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005128.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005129.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005130.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005131.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005134.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005135.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005138.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005139.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005142.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005143.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005144.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005145.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005146.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005147.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005148.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005149.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005150.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005151.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005152.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005153.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005156.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005157.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005160.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005161.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005162.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005163.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005164.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005165.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005166.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005167.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005168.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005169.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005170.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005171.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005172.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005173.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005175.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005176.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005178.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005179.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005181.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005182.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005184.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005185.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005186.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005187.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005188.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005189.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005190.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005191.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005193.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005194.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005196.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005197.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005199.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005200.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005202.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005203.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005206.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005207.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005210.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005211.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005212.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005213.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005214.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005215.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005216.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005217.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005218.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005219.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005220.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005221.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005222.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005227.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005228.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005229.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005230.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005231.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005232.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005233.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005235.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005236.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005238.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005239.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005241.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005242.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005244.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005245.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005246.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005247.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005248.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005253.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005254.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005255.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005256.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005257.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005260.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005261.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005264.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005265.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005268.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005269.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005272.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005273.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005276.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005277.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005278.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005279.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005280.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005281.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005282.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005283.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005284.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005285.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005286.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005287.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005290.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005291.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005294.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005295.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005296.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005297.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005298.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005299.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005300.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005301.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005302.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005303.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005304.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005305.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005306.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005307.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005309.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005310.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005312.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005313.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005315.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005316.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005318.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005319.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005320.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005321.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005322.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005323.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005324.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005325.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005327.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005328.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005330.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005331.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005333.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005334.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005336.inp --no-xml-output
date

rm -rf $TMPDIR
