#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main11.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000007931.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007933.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007934.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007936.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007937.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007939.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007940.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007942.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007943.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007945.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007946.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007948.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007949.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007951.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007952.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007954.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007955.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007956.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007957.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007958.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007963.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007964.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007965.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007966.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007967.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007968.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007969.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007971.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007972.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007974.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007975.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007977.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007978.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007980.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007981.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007983.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007984.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007986.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007987.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007989.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007990.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007992.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007993.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007995.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007996.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007998.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007999.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008001.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008002.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008004.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008005.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008007.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008008.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008010.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008011.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008013.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008014.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008016.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008017.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008019.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008020.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008022.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008023.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008025.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008026.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008028.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008029.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008030.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008031.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008032.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008037.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008038.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008039.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008040.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008041.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008044.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008045.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008048.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008049.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008052.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008053.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008056.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008057.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008060.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008061.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008064.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008065.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008068.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008069.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008072.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008073.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008076.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008077.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008080.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008081.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008084.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008085.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008088.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008089.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008092.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008093.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008094.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008095.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008096.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008097.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008098.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008099.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008100.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008101.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008102.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008103.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008106.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008107.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008110.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008111.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008112.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008113.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008114.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008115.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008116.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008117.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008118.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008119.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008120.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008121.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008122.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008123.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008125.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008126.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008128.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008129.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008131.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008132.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008134.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008135.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008136.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008137.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008138.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008139.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008140.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008141.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008143.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008144.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008146.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008147.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008149.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008150.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008152.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008153.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008156.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008157.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008160.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008161.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008162.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008163.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008164.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008165.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008166.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008167.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008168.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008169.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008170.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008171.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008172.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008173.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008175.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008176.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008178.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008179.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008181.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008182.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008184.inp --no-xml-output
date

rm -rf $TMPDIR
