#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main18.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000009725.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009727.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009728.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009730.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009731.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009733.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009734.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009736.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009737.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009740.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009741.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009744.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009745.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009746.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009747.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009748.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009752.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009753.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009754.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009755.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009756.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009757.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009758.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009759.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009760.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009761.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009766.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009767.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009768.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009769.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009770.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009771.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009772.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009774.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009775.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009777.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009778.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009780.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009781.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009783.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009784.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009785.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009786.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009787.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009792.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009793.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009794.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009795.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009796.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009797.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009798.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009800.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009801.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009803.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009804.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009806.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009807.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009809.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009810.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009812.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009813.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009815.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009816.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009818.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009819.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009821.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009822.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009823.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009824.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009825.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009830.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009831.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009832.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009833.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009834.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009835.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009836.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009838.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009839.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009841.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009842.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009844.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009845.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009847.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009848.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009850.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009851.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009853.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009854.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009856.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009857.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009859.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009860.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009862.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009863.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009865.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009866.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009868.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009869.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009871.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009872.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009873.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009874.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009875.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009880.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009881.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009882.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009883.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009884.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009885.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009886.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009888.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009889.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009891.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009892.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009894.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009895.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009897.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009898.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009900.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009901.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009903.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009904.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009906.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009907.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009909.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009910.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009912.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009913.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009915.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009916.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009918.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009919.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009921.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009922.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009924.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009925.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009927.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009928.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009930.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009931.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009933.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009934.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009935.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009936.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009937.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009942.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009943.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009944.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009945.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009946.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009947.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009948.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009950.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009951.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009953.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009954.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009956.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009957.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009959.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009960.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009962.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009963.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009965.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009966.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009968.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009969.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009971.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009972.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009974.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009975.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009977.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009978.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009980.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009981.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009983.inp --no-xml-output
date

rm -rf $TMPDIR
