#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main29.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000012605.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012607.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012608.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012610.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012611.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012613.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012614.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012616.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012617.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012618.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012619.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012620.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012625.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012626.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012627.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012628.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012629.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012632.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012633.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012636.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012637.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012640.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012641.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012644.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012645.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012648.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012649.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012652.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012653.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012656.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012657.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012660.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012661.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012664.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012665.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012668.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012669.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012672.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012673.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012676.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012677.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012680.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012681.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012684.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012685.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012688.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012689.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012692.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012693.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012696.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012697.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012698.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012699.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012700.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012701.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012702.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012703.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012704.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012707.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012708.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012709.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012710.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012713.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012714.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012715.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012716.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012717.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012718.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012719.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012722.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012723.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012726.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012727.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012728.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012729.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012730.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012733.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012734.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012735.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012736.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012739.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012740.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012741.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012742.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012743.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012744.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012745.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012746.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012747.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012749.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012750.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012752.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012753.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012755.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012756.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012758.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012759.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012760.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012761.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012762.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012763.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012764.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012765.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012767.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012768.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012770.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012771.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012773.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012774.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012776.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012777.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012780.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012781.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012784.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012785.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012786.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012787.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012788.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012791.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012792.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012793.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012794.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012797.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012798.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012799.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012800.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012801.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012802.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012803.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012804.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012805.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012807.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012808.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012810.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012811.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012813.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012814.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012816.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012817.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012818.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012819.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012820.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012821.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012822.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012823.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012824.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012825.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012826.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012827.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012828.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012829.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012830.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012831.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012832.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012833.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012834.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012835.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012836.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012837.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012838.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012839.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012840.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012841.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012843.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012844.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012846.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012847.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012849.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012850.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012852.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012853.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012854.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012855.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012856.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012857.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012858.inp --no-xml-output
date

rm -rf $TMPDIR
