#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main47.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000017333.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017335.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017336.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017338.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017339.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017341.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017342.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017344.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017345.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017346.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017347.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017348.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017349.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017350.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017351.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017352.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017353.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017354.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017355.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017356.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017357.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017358.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017359.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017360.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017361.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017362.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017363.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017364.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017365.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017366.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017367.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017368.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017369.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017370.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017371.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017372.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017373.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017374.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017375.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017376.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017377.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017378.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017379.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017380.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017381.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017382.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017383.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017384.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017385.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017386.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017387.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017388.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017389.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017390.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017391.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017392.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017393.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017394.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017395.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017396.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017397.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017398.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017399.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017400.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017401.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017402.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017403.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017404.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017405.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017406.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017407.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017408.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017409.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017410.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017411.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017412.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017413.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017414.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017415.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017416.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017417.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017418.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017419.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017420.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017421.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017422.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017423.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017424.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017425.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017426.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017427.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017428.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017429.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017430.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017431.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017432.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017433.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017434.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017435.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017436.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017437.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017438.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017439.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017440.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017441.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017442.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017443.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017444.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017445.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017446.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017447.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017448.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017449.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017451.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017452.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017454.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017455.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017457.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017458.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017460.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017461.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017462.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017463.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017464.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017465.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017466.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017467.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017469.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017470.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017472.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017473.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017475.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017476.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017478.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017479.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017481.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017482.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017484.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017485.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017487.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017488.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017490.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017491.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017493.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017494.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017496.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017497.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017499.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017500.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017502.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017503.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017505.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017506.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017508.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017509.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017511.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017512.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017514.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017515.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017517.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017518.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017520.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017521.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017523.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017524.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017526.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017527.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017529.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017530.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017532.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017533.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017535.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017536.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017538.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017539.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017541.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017542.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017544.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017545.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017547.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017548.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017550.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017551.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017554.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017555.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017558.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017559.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017560.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017561.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017562.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017563.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017564.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017565.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017566.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017567.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017568.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017569.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017570.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017571.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017573.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017574.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017576.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017577.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017579.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017580.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017582.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017583.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017584.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017585.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017586.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017587.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017588.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017589.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000017590.inp --no-xml-output
date

rm -rf $TMPDIR
