#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main56.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000019692.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019695.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019696.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019699.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019700.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019701.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019702.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019703.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019707.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019708.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019709.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019710.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019711.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019712.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019713.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019714.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019715.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019716.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019721.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019722.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019723.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019724.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019725.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019726.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019727.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019729.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019730.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019732.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019733.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019735.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019736.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019738.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019739.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019740.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019741.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019742.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019747.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019748.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019749.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019750.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019751.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019752.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019753.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019755.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019756.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019758.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019759.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019761.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019762.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019764.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019765.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019767.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019768.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019770.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019771.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019773.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019774.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019776.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019777.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019778.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019779.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019780.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019785.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019786.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019787.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019788.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019789.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019790.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019791.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019793.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019794.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019796.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019797.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019799.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019800.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019802.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019803.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019805.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019806.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019808.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019809.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019811.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019812.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019814.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019815.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019817.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019818.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019820.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019821.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019823.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019824.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019826.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019827.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019828.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019829.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019830.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019835.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019836.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019837.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019838.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019839.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019840.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019841.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019843.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019844.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019846.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019847.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019849.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019850.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019852.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019853.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019855.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019856.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019858.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019859.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019861.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019862.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019864.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019865.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019867.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019868.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019870.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019871.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019873.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019874.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019876.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019877.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019879.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019880.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019882.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019883.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019885.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019886.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019888.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019889.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019890.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019891.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019892.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019897.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019898.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019899.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019900.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019901.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019902.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019903.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019905.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019906.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019908.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019909.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019911.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019912.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019914.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019915.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019917.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019918.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019920.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019921.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019923.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019924.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019926.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019927.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019929.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019930.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019932.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019933.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019935.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019936.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019938.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019939.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019941.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019942.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019944.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019945.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019947.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019948.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019950.inp --no-xml-output
date

rm -rf $TMPDIR
