#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main10.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000007669.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007670.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007671.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007672.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007673.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007674.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007675.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007676.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007677.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007678.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007679.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007680.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007681.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007682.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007683.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007684.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007685.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007687.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007688.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007690.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007691.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007693.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007694.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007696.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007697.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007698.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007699.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007700.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007701.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007702.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007703.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007705.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007706.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007708.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007709.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007711.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007712.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007714.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007715.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007717.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007718.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007720.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007721.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007723.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007724.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007726.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007727.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007729.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007730.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007732.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007733.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007735.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007736.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007738.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007739.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007741.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007742.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007744.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007745.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007747.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007748.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007750.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007751.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007753.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007754.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007756.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007757.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007759.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007760.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007762.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007763.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007766.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007767.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007770.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007771.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007772.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007773.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007774.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007775.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007776.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007777.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007778.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007779.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007780.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007781.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007782.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007787.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007788.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007789.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007790.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007791.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007792.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007793.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007795.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007796.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007798.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007799.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007801.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007802.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007804.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007805.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007806.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007807.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007808.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007813.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007814.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007815.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007816.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007817.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007818.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007819.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007821.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007822.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007824.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007825.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007827.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007828.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007830.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007831.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007833.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007834.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007836.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007837.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007839.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007840.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007842.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007843.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007844.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007845.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007846.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007851.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007852.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007853.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007854.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007855.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007856.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007857.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007859.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007860.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007862.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007863.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007865.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007866.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007868.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007869.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007871.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007872.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007874.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007875.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007877.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007878.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007880.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007881.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007883.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007884.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007886.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007887.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007889.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007890.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007892.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007893.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007894.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007895.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007896.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007901.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007902.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007903.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007904.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007905.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007906.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007907.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007909.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007910.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007912.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007913.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007915.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007916.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007918.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007919.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007921.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007922.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007924.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007925.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007927.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007928.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000007930.inp --no-xml-output
date

rm -rf $TMPDIR
