#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main1.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000005327.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005330.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005331.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005332.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005333.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005334.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005335.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005336.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005337.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005338.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005341.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005342.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005343.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005344.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005347.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005348.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005349.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005350.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005351.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005352.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005353.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005356.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005357.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005360.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005361.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005362.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005363.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005364.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005367.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005368.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005369.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005370.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005373.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005374.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005375.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005376.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005377.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005378.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005379.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005380.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005381.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005383.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005384.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005386.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005387.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005389.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005390.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005392.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005393.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005394.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005395.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005396.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005397.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005398.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005399.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005401.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005402.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005404.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005405.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005407.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005408.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005410.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005411.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005414.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005415.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005418.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005419.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005420.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005421.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005422.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005425.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005426.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005427.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005428.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005431.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005432.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005433.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005434.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005435.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005436.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005437.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005438.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005439.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005441.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005442.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005444.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005445.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005447.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005448.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005450.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005451.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005452.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005453.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005454.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005455.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005456.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005457.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005458.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005459.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005460.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005461.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005462.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005463.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005464.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005465.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005466.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005467.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005468.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005469.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005470.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005471.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005472.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005473.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005474.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005475.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005477.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005478.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005480.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005481.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005483.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005484.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005486.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005487.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005488.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005489.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005490.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005491.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005492.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005493.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005495.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005496.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005498.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005499.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005501.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005502.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005504.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005505.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005507.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005508.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005510.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005511.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005513.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005514.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005516.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005517.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005520.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005521.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005524.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005525.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005526.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005527.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005528.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005532.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005533.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005534.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005535.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005536.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005537.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005538.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005539.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005540.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005541.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005546.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005547.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005548.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005549.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005550.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005551.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005552.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005554.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005555.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005557.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005558.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005560.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005561.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005563.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005564.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005565.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005566.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005567.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005572.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005573.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005574.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005575.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005576.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005577.inp --no-xml-output
date

rm -rf $TMPDIR
