#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main18.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000009747.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009749.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009750.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009752.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009753.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009755.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009756.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009758.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009759.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009761.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009762.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009764.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009765.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009767.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009768.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009770.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009771.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009773.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009774.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009776.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009777.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009779.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009780.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009782.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009783.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009785.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009786.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009788.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009789.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009791.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009792.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009794.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009795.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009796.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009797.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009798.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009803.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009804.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009805.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009806.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009807.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009810.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009811.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009814.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009815.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009818.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009819.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009822.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009823.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009826.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009827.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009830.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009831.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009834.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009835.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009838.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009839.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009842.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009843.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009846.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009847.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009850.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009851.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009854.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009855.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009858.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009859.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009862.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009863.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009866.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009867.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009868.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009869.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009870.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009871.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009872.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009873.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009874.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009875.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009876.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009877.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009880.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009881.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009884.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009885.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009886.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009887.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009888.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009889.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009890.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009891.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009892.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009893.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009894.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009895.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009896.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009897.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009899.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009900.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009902.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009903.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009905.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009906.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009908.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009909.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009910.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009911.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009912.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009913.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009914.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009915.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009917.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009918.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009920.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009921.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009923.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009924.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009926.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009927.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009930.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009931.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009934.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009935.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009936.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009937.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009938.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009939.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009940.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009941.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009942.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009943.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009944.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009945.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009946.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009947.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009949.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009950.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009952.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009953.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009955.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009956.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009958.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009959.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009960.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009961.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009962.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009963.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009964.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009965.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009966.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009967.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009968.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009969.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009970.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009971.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009972.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009973.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009974.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009975.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009976.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009977.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009978.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009979.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009980.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009981.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009982.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009983.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009985.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009986.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009988.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009989.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009991.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009992.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009994.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009995.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009996.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009997.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009998.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009999.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000010000.inp --no-xml-output
date

rm -rf $TMPDIR
