#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main0.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000005083.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005084.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005086.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005087.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005088.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005089.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005090.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005091.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005092.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005093.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005097.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005098.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005099.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005100.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005101.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005104.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005105.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005106.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005107.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005108.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005109.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005110.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005111.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005112.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005115.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005116.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005117.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005118.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005121.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005122.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005123.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005124.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005125.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005126.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005127.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005130.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005131.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005134.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005135.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005136.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005137.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005138.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005142.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005143.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005144.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005145.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005146.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005147.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005148.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005149.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005150.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005151.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005156.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005157.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005158.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005159.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005160.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005163.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005164.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005167.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005168.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005171.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005172.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005173.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005174.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005175.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005176.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005177.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005178.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005179.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005182.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005183.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005184.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005185.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005188.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005189.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005190.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005191.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005192.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005193.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005194.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005197.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005198.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005201.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005202.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005203.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005204.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005205.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005208.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005209.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005210.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005211.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005214.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005215.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005216.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005217.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005218.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005219.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005220.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005221.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005222.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005224.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005225.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005227.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005228.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005230.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005231.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005233.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005234.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005235.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005236.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005237.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005238.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005239.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005240.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005242.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005243.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005245.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005246.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005248.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005249.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005251.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005252.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005255.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005256.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005259.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005260.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005261.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005262.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005263.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005267.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005268.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005269.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005270.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005271.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005272.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005273.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005274.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005275.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005276.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005281.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005282.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005283.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005284.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005285.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005286.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005287.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005289.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005290.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005292.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005293.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005295.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005296.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005298.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005299.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005300.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005301.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005302.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005307.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005308.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005309.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005310.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005311.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005314.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005315.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005318.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005319.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005322.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005323.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005326.inp --no-xml-output
date

rm -rf $TMPDIR
