#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main13.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000008421.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008422.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008423.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008424.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008427.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008428.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008429.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008430.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008431.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008432.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008433.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008434.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008435.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008437.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008438.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008440.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008441.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008443.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008444.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008446.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008447.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008448.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008449.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008450.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008451.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008452.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008453.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008454.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008455.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008456.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008457.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008458.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008459.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008460.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008461.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008462.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008463.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008464.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008465.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008466.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008467.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008468.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008469.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008470.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008471.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008473.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008474.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008476.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008477.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008479.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008480.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008482.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008483.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008484.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008485.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008486.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008487.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008488.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008489.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008491.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008492.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008494.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008495.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008497.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008498.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008500.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008501.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008503.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008504.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008506.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008507.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008509.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008510.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008512.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008513.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008516.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008517.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008520.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008521.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008522.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008523.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008524.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008527.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008528.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008529.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008530.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008533.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008534.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008535.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008536.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008537.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008538.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008539.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008540.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008541.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008543.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008544.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008546.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008547.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008549.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008550.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008552.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008553.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008554.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008555.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008556.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008557.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008558.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008559.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008560.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008561.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008562.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008563.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008564.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008565.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008566.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008567.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008568.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008569.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008570.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008571.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008572.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008573.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008574.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008575.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008576.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008577.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008579.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008580.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008582.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008583.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008585.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008586.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008588.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008589.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008590.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008591.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008592.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008593.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008594.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008595.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008596.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008597.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008598.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008599.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008600.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008601.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008602.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008603.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008604.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008605.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008606.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008607.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008608.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008609.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008610.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008611.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008612.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008613.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008614.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008615.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008616.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008617.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008618.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008619.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008620.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008621.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008622.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008623.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008624.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008625.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008626.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008627.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008628.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008629.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008631.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008632.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008634.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008635.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008637.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008638.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008640.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008641.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008642.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008643.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008644.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008645.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008646.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008647.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008649.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008650.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008652.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008653.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008655.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008656.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008658.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008659.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008661.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008662.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008664.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008665.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008667.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008668.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008670.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008671.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008673.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008674.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008676.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008677.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008679.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008680.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000008682.inp --no-xml-output
date

rm -rf $TMPDIR
