#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main16.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000009237.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009238.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009239.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009240.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009241.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009242.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009243.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009244.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009245.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009246.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009247.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009248.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009249.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009250.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009251.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009252.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009253.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009255.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009256.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009258.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009259.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009261.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009262.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009264.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009265.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009266.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009267.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009268.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009269.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009270.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009271.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009272.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009273.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009274.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009275.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009276.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009277.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009278.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009279.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009280.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009281.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009282.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009283.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009284.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009285.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009286.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009287.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009288.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009289.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009290.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009291.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009292.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009293.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009294.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009295.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009296.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009297.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009298.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009299.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009300.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009301.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009302.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009303.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009304.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009305.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009306.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009307.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009308.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009309.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009310.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009311.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009312.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009313.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009314.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009315.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009316.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009317.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009318.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009319.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009320.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009321.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009322.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009323.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009324.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009325.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009326.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009327.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009328.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009329.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009330.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009331.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009332.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009333.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009334.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009335.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009336.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009337.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009338.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009339.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009340.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009341.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009342.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009343.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009344.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009345.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009346.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009347.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009348.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009349.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009350.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009351.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009352.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009353.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009355.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009356.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009358.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009359.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009361.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009362.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009364.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009365.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009366.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009367.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009368.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009369.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009370.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009371.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009373.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009374.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009376.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009377.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009379.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009380.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009382.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009383.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009385.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009386.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009388.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009389.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009391.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009392.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009394.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009395.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009397.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009398.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009400.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009401.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009403.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009404.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009406.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009407.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009409.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009410.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009412.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009413.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009415.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009416.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009418.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009419.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009421.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009422.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009424.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009425.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009427.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009428.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009430.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009431.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009433.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009434.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009436.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009437.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009439.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009440.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009442.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009443.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009446.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009447.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009450.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009451.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009452.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009453.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009454.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009455.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009456.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009457.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009458.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009459.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009460.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009461.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009462.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009467.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009468.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009469.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009470.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009471.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009472.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009473.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009475.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009476.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009478.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009479.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009481.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009482.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009484.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009485.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009486.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009487.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009488.inp --no-xml-output
date

rm -rf $TMPDIR
