#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main59.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000020463.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020466.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020467.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020470.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020471.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020474.inp --no-xml-output
date

rm -rf $TMPDIR
