#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main54.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000019163.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019164.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019165.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019166.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019167.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019168.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019169.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019170.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019171.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019172.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019173.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019174.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019179.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019180.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019181.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019182.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019183.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019184.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019185.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019187.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019188.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019190.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019191.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019193.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019194.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019196.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019197.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019198.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019199.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019200.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019205.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019206.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019207.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019208.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019209.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019210.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019211.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019213.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019214.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019216.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019217.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019219.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019220.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019222.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019223.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019225.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019226.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019228.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019229.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019231.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019232.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019234.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019235.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019236.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019237.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019238.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019243.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019244.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019245.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019246.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019247.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019248.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019249.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019251.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019252.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019254.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019255.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019257.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019258.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019260.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019261.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019263.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019264.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019266.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019267.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019269.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019270.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019272.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019273.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019275.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019276.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019278.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019279.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019281.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019282.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019284.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019285.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019286.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019287.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019288.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019293.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019294.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019295.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019296.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019297.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019298.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019299.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019301.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019302.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019304.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019305.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019307.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019308.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019310.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019311.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019313.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019314.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019316.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019317.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019319.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019320.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019322.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019323.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019325.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019326.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019328.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019329.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019331.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019332.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019334.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019335.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019337.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019338.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019340.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019341.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019343.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019344.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019346.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019347.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019348.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019349.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019350.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019355.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019356.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019357.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019358.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019359.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019360.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019361.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019363.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019364.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019366.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019367.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019369.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019370.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019372.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019373.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019375.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019376.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019378.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019379.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019381.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019382.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019384.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019385.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019387.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019388.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019390.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019391.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019393.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019394.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019396.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019397.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019399.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019400.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019402.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019403.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019405.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019406.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019408.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019409.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019411.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019412.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019414.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019415.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019417.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019418.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019420.inp --no-xml-output
date

rm -rf $TMPDIR
