#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main40.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000015487.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015489.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015490.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015492.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015493.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015495.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015496.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015498.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015499.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015501.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015502.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015504.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015505.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015507.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015508.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015510.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015511.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015513.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015514.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015516.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015517.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015519.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015520.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015522.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015523.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015525.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015526.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015528.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015529.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015531.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015532.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015534.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015535.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015536.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015537.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015538.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015543.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015544.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015545.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015546.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015547.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015550.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015551.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015554.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015555.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015558.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015559.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015562.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015563.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015566.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015567.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015570.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015571.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015574.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015575.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015578.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015579.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015582.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015583.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015586.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015587.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015590.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015591.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015594.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015595.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015598.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015599.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015602.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015603.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015606.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015607.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015610.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015611.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015614.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015615.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015618.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015619.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015622.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015623.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015624.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015625.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015626.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015627.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015628.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015629.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015630.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015631.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015632.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015633.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015636.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015637.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015640.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015641.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015642.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015643.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015644.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015645.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015646.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015647.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015648.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015649.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015650.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015651.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015652.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015653.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015655.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015656.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015658.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015659.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015661.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015662.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015664.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015665.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015666.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015667.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015668.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015669.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015670.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015671.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015673.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015674.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015676.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015677.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015679.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015680.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015682.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015683.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015686.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015687.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015690.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015691.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015692.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015693.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015694.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015695.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015696.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015697.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015698.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015699.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015700.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015701.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015702.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015703.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015705.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015706.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015708.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015709.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015711.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015712.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015714.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015715.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015716.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015717.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015718.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015719.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015720.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015721.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015722.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015723.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015724.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015725.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015726.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015727.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015728.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015729.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015730.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015731.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015732.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015733.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015734.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015735.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015736.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015737.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015738.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015739.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015741.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015742.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015744.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015745.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015747.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015748.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015750.inp --no-xml-output
date

rm -rf $TMPDIR
