#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main57.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000019951.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019953.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019954.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019956.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019957.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019959.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019960.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019962.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019963.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019964.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019965.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019966.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019971.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019972.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019973.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019974.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019975.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019976.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019977.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019979.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019980.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019982.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019983.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019985.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019986.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019988.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019989.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019991.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019992.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019994.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019995.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019997.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019998.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020000.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020001.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020003.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020004.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020006.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020007.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020009.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020010.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020012.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020013.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020015.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020016.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020018.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020019.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020021.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020022.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020024.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020025.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020027.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020028.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020030.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020031.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020033.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020034.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020036.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020037.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020039.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020040.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020042.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020043.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020045.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020046.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020048.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020049.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020050.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020051.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020052.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020057.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020058.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020059.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020060.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020061.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020062.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020063.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020065.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020066.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020068.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020069.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020071.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020072.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020074.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020075.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020077.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020078.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020080.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020081.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020083.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020084.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020086.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020087.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020089.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020090.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020092.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020093.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020095.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020096.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020098.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020099.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020101.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020102.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020104.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020105.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020107.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020108.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020110.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020111.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020113.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020114.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020116.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020117.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020119.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020120.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020122.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020123.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020125.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020126.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020128.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020129.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020131.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020132.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020134.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020135.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020137.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020138.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020140.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020141.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020143.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020144.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020146.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020147.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020148.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020149.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020150.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020155.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020156.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020157.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020158.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020159.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020160.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020161.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020163.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020164.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020166.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020167.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020169.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020170.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020172.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020173.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020175.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020176.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020178.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020179.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020181.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020182.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020184.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020185.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020187.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020188.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020190.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020191.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020193.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020194.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020196.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020197.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020199.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020200.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020202.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020203.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020205.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020206.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000020208.inp --no-xml-output
date

rm -rf $TMPDIR
