#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main6.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000006631.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006632.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006633.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006634.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006639.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006640.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006641.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006642.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006643.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006644.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006645.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006647.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006648.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006650.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006651.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006653.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006654.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006656.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006657.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006658.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006659.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006660.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006665.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006666.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006667.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006668.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006669.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006670.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006671.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006673.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006674.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006676.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006677.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006679.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006680.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006682.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006683.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006685.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006686.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006688.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006689.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006691.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006692.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006694.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006695.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006696.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006697.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006698.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006703.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006704.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006705.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006706.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006707.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006708.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006709.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006711.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006712.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006714.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006715.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006717.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006718.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006720.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006721.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006723.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006724.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006726.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006727.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006729.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006730.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006732.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006733.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006735.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006736.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006738.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006739.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006741.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006742.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006744.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006745.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006746.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006747.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006748.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006753.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006754.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006755.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006756.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006757.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006758.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006759.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006761.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006762.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006764.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006765.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006767.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006768.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006770.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006771.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006773.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006774.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006776.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006777.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006779.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006780.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006782.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006783.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006785.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006786.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006788.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006789.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006791.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006792.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006794.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006795.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006797.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006798.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006800.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006801.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006803.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006804.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006806.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006807.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006808.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006809.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006810.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006815.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006816.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006817.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006818.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006819.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006822.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006823.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006826.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006827.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006830.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006831.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006834.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006835.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006838.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006839.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006842.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006843.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006846.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006847.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006850.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006851.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006854.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006855.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006858.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006859.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006862.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006863.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006864.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006865.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006866.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006867.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006868.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006869.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006870.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006871.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006872.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006873.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006876.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006877.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000006880.inp --no-xml-output
date

rm -rf $TMPDIR
