#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main26.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000011837.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011838.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011839.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011840.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011845.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011846.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011847.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011848.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011849.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011850.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011851.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011853.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011854.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011856.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011857.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011859.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011860.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011862.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011863.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011865.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011866.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011868.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011869.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011871.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011872.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011874.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011875.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011876.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011877.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011878.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011883.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011884.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011885.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011886.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011887.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011888.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011889.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011891.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011892.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011894.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011895.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011897.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011898.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011900.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011901.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011903.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011904.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011906.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011907.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011909.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011910.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011912.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011913.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011915.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011916.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011918.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011919.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011921.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011922.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011924.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011925.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011926.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011927.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011928.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011933.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011934.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011935.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011936.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011937.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011938.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011939.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011941.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011942.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011944.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011945.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011947.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011948.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011950.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011951.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011953.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011954.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011956.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011957.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011959.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011960.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011962.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011963.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011965.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011966.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011968.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011969.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011971.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011972.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011974.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011975.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011977.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011978.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011980.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011981.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011983.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011984.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011986.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011987.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011988.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011989.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011990.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011995.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011996.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011997.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011998.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000011999.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012000.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012001.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012003.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012004.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012006.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012007.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012009.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012010.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012012.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012013.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012015.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012016.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012018.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012019.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012021.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012022.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012024.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012025.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012027.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012028.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012030.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012031.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012033.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012034.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012036.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012037.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012039.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012040.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012042.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012043.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012045.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012046.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012048.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012049.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012051.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012052.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012054.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012055.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012057.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012058.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012060.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012061.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012062.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012063.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012064.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012069.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012070.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012071.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012072.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012073.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012074.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012075.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012077.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012078.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012080.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012081.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012083.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012084.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012086.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012087.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012089.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012090.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012092.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012093.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012095.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012096.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000012098.inp --no-xml-output
date

rm -rf $TMPDIR
