#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main38.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000014975.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000014978.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000014979.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000014982.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000014983.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000014984.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000014985.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000014986.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000014987.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000014988.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000014989.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000014990.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000014991.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000014992.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000014993.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000014994.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000014999.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015000.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015001.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015002.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015003.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015004.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015005.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015007.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015008.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015010.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015011.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015013.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015014.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015016.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015017.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015018.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015019.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015020.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015025.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015026.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015027.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015028.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015029.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015030.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015031.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015033.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015034.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015036.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015037.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015039.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015040.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015042.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015043.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015045.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015046.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015048.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015049.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015051.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015052.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015054.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015055.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015056.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015057.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015058.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015063.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015064.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015065.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015066.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015067.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015068.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015069.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015071.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015072.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015074.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015075.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015077.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015078.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015080.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015081.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015083.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015084.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015086.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015087.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015089.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015090.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015092.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015093.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015095.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015096.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015098.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015099.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015101.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015102.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015104.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015105.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015106.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015107.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015108.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015113.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015114.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015115.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015116.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015117.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015118.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015119.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015121.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015122.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015124.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015125.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015127.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015128.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015130.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015131.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015133.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015134.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015136.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015137.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015139.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015140.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015142.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015143.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015145.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015146.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015148.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015149.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015151.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015152.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015154.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015155.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015157.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015158.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015160.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015161.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015163.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015164.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015166.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015167.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015168.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015169.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015170.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015175.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015176.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015177.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015178.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015179.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015180.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015181.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015183.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015184.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015186.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015187.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015189.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015190.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015192.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015193.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015195.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015196.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015198.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015199.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015201.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015202.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015204.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015205.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015207.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015208.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015210.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015211.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015213.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015214.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015216.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015217.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015219.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015220.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015222.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015223.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015225.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015226.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015228.inp --no-xml-output
date

rm -rf $TMPDIR
