#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main56.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000019679.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019681.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019682.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019684.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019685.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019687.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019688.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019690.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019691.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019693.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019694.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019696.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019697.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019699.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019700.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019702.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019703.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019705.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019706.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019708.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019709.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019711.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019712.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019714.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019715.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019716.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019717.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019718.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019723.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019724.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019725.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019726.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019727.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019728.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019729.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019731.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019732.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019734.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019735.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019737.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019738.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019740.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019741.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019743.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019744.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019746.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019747.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019749.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019750.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019752.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019753.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019755.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019756.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019758.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019759.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019761.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019762.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019764.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019765.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019767.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019768.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019770.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019771.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019773.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019774.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019776.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019777.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019779.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019780.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019782.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019783.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019785.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019786.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019788.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019789.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019791.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019792.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019794.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019795.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019797.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019798.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019800.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019801.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019803.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019804.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019806.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019807.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019809.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019810.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019812.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019813.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019815.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019816.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019818.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019819.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019821.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019822.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019824.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019825.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019827.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019828.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019830.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019831.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019833.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019834.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019836.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019837.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019838.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019839.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019840.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019845.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019846.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019847.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019848.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019849.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019852.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019853.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019856.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019857.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019860.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019861.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019864.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019865.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019868.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019869.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019872.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019873.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019876.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019877.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019880.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019881.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019884.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019885.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019888.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019889.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019892.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019893.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019896.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019897.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019900.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019901.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019904.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019905.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019908.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019909.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019912.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019913.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019916.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019917.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019920.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019921.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019924.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019925.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019928.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019929.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000019932.inp --no-xml-output
date

rm -rf $TMPDIR
