#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main40.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000015484.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015486.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015487.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015489.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015490.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015492.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015493.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015495.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015496.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015498.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015499.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015501.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015502.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015504.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015505.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015507.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015508.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015509.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015510.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015511.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015516.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015517.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015518.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015519.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015520.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015521.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015522.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015524.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015525.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015527.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015528.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015530.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015531.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015533.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015534.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015536.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015537.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015539.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015540.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015542.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015543.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015545.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015546.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015548.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015549.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015551.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015552.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015554.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015555.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015557.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015558.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015559.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015560.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015561.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015566.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015567.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015568.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015569.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015570.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015571.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015572.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015574.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015575.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015577.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015578.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015580.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015581.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015583.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015584.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015586.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015587.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015589.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015590.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015592.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015593.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015595.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015596.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015598.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015599.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015601.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015602.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015604.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015605.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015607.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015608.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015610.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015611.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015613.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015614.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015616.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015617.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015619.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015620.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015621.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015622.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015623.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015628.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015629.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015630.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015631.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015632.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015633.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015634.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015636.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015637.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015639.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015640.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015642.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015643.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015645.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015646.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015648.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015649.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015651.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015652.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015654.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015655.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015657.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015658.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015660.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015661.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015663.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015664.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015666.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015667.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015669.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015670.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015672.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015673.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015675.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015676.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015678.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015679.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015681.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015682.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015684.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015685.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015687.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015688.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015690.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015691.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015693.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015694.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015695.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015696.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015697.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015702.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015703.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015704.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015705.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015706.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015707.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015708.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015710.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015711.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015713.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015714.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015716.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015717.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015719.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015720.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015722.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015723.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015725.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015726.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015728.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015729.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015731.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015732.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015734.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015735.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015737.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015738.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015740.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015741.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000015743.inp --no-xml-output
date

rm -rf $TMPDIR
