#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main2.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000005578.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005580.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005581.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005583.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005584.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005586.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005587.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005589.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005590.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005592.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005593.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005595.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005596.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005598.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005599.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005601.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005602.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005603.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005604.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005605.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005610.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005611.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005612.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005613.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005614.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005617.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005618.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005621.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005622.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005625.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005626.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005629.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005630.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005633.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005634.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005637.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005638.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005641.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005642.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005643.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005644.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005645.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005646.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005647.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005648.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005649.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005652.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005653.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005654.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005655.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005658.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005659.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005660.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005661.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005662.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005663.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005664.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005667.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005668.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005671.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005672.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005673.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005674.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005675.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005678.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005679.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005680.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005681.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005684.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005685.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005686.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005687.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005688.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005689.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005690.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005691.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005692.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005694.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005695.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005697.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005698.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005700.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005701.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005703.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005704.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005705.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005706.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005707.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005708.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005709.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005710.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005712.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005713.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005715.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005716.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005718.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005719.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005721.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005722.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005725.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005726.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005729.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005730.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005731.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005732.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005733.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005736.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005737.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005738.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005739.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005742.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005743.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005744.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005745.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005746.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005747.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005748.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005749.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005750.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005752.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005753.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005755.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005756.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005758.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005759.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005761.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005762.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005763.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005764.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005765.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005766.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005767.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005768.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005769.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005770.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005771.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005772.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005773.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005774.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005775.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005776.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005777.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005778.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005779.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005780.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005781.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005782.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005783.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005784.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005785.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005786.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005788.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005789.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005791.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005792.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005794.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005795.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005797.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005798.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005799.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005800.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005801.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005802.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005803.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005804.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005806.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005807.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005809.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005810.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005812.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005813.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005815.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005816.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005818.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005819.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005821.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005822.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005824.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005825.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005827.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005828.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005831.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005832.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000005835.inp --no-xml-output
date

rm -rf $TMPDIR
