#!/bin/sh
#PBS -N CH2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2co/pts/inp/main17.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2co/pts/inp/job.0000009493.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009494.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009495.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009496.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009497.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009498.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009499.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009501.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009502.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009504.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009505.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009507.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009508.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009510.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009511.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009513.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009514.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009516.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009517.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009519.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009520.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009522.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009523.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009524.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009525.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009526.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009531.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009532.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009533.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009534.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009535.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009536.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009537.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009539.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009540.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009542.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009543.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009545.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009546.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009548.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009549.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009551.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009552.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009554.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009555.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009557.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009558.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009560.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009561.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009563.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009564.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009566.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009567.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009569.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009570.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009572.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009573.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009574.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009575.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009576.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009581.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009582.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009583.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009584.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009585.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009586.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009587.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009589.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009590.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009592.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009593.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009595.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009596.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009598.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009599.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009601.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009602.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009604.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009605.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009607.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009608.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009610.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009611.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009613.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009614.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009616.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009617.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009619.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009620.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009622.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009623.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009625.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009626.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009628.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009629.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009631.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009632.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009634.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009635.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009636.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009637.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009638.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009643.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009644.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009645.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009646.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009647.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009648.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009649.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009651.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009652.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009654.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009655.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009657.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009658.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009660.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009661.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009663.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009664.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009666.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009667.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009669.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009670.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009672.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009673.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009675.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009676.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009678.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009679.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009681.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009682.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009684.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009685.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009687.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009688.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009690.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009691.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009693.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009694.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009696.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009697.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009699.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009700.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009702.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009703.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009705.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009706.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009708.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009709.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009710.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009711.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009712.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009717.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009718.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009719.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009720.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009721.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009722.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009723.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009725.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009726.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009728.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009729.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009731.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009732.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009734.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009735.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009737.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009738.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009740.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009741.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009743.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009744.inp --no-xml-output
molpro -t 1 tests/cart/h2co/pts/inp/job.0000009746.inp --no-xml-output
date

rm -rf $TMPDIR
