#!/bin/sh
#PBS -N H2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2o/pts/inp/main1.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2o/pts/inp/job.0000000244.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000247.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000248.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000249.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000250.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000251.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000252.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000253.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000254.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000255.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000258.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000259.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000260.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000261.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000264.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000265.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000266.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000267.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000268.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000269.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000270.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000273.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000274.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000277.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000278.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000279.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000280.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000281.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000284.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000285.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000286.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000287.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000290.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000291.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000292.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000293.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000294.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000295.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000296.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000297.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000298.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000300.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000301.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000303.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000304.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000306.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000307.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000309.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000310.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000311.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000312.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000313.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000314.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000315.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000316.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000318.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000319.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000321.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000322.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000324.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000325.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000327.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000328.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000331.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000332.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000335.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000336.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000337.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000338.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000339.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000342.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000343.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000344.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000345.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000348.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000349.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000350.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000351.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000352.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000353.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000354.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000355.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000356.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000358.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000359.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000361.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000362.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000364.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000365.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000367.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000368.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000369.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000370.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000371.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000372.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000373.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000374.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000375.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000376.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000377.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000378.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000379.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000380.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000381.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000382.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000383.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000384.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000385.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000386.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000387.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000388.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000389.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000390.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000391.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000392.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000394.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000395.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000397.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000398.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000400.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000401.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000403.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000404.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000405.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000406.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000407.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000408.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000409.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000410.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000412.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000413.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000415.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000416.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000418.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000419.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000421.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000422.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000424.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000425.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000427.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000428.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000430.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000431.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000433.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000434.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000437.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000438.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000441.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000442.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000443.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000444.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000445.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000449.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000450.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000451.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000452.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000453.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000454.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000455.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000456.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000457.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000458.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000463.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000464.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000465.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000466.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000467.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000468.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000469.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000471.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000472.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000474.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000475.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000477.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000478.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000480.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000481.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000482.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000483.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000484.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000489.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000490.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000491.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000492.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000493.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000494.inp --no-xml-output
date

rm -rf $TMPDIR
