#!/bin/sh
#PBS -N H2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2o/pts/inp/main11.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2o/pts/inp/job.0000002831.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002833.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002834.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002836.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002837.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002839.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002840.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002842.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002843.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002844.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002845.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002846.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002847.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002848.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002849.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002851.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002852.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002854.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002855.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002857.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002858.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002860.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002861.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002863.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002864.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002866.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002867.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002869.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002870.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002872.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002873.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002875.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002876.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002878.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002879.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002881.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002882.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002884.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002885.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002887.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002888.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002890.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002891.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002893.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002894.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002896.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002897.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002899.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002900.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002902.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002903.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002905.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002906.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002908.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002909.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002912.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002913.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002916.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002917.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002918.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002919.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002920.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002924.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002925.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002926.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002927.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002928.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002929.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002930.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002931.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002932.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002933.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002938.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002939.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002940.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002941.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002942.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002943.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002944.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002946.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002947.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002949.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002950.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002952.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002953.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002955.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002956.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002957.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002958.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002959.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002964.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002965.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002966.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002967.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002968.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002969.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002970.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002972.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002973.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002975.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002976.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002978.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002979.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002981.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002982.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002984.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002985.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002987.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002988.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002990.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002991.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002993.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002994.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002995.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002996.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000002997.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003002.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003003.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003004.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003005.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003006.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003007.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003008.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003010.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003011.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003013.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003014.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003016.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003017.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003019.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003020.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003022.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003023.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003025.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003026.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003028.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003029.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003031.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003032.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003034.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003035.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003037.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003038.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003040.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003041.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003043.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003044.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003045.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003046.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003047.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003052.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003053.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003054.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003055.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003056.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003057.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003058.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003060.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003061.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003063.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003064.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003066.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003067.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003069.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003070.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003072.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003073.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003075.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003076.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003078.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003079.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003081.inp --no-xml-output
date

rm -rf $TMPDIR
