#!/bin/sh
#PBS -N H2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2o/pts/inp/main4.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2o/pts/inp/job.0000001008.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001009.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001010.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001011.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001012.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001013.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001014.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001016.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001017.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001019.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001020.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001022.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001023.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001025.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001026.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001028.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001029.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001031.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001032.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001034.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001035.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001037.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001038.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001040.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001041.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001043.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001044.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001046.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001047.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001049.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001050.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001051.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001052.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001053.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001058.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001059.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001060.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001061.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001062.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001065.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001066.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001069.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001070.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001073.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001074.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001077.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001078.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001081.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001082.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001085.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001086.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001089.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001090.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001093.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001094.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001097.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001098.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001099.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001100.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001101.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001102.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001103.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001104.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001105.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001108.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001109.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001110.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001111.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001114.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001115.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001116.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001117.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001118.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001119.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001120.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001123.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001124.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001127.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001128.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001129.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001130.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001131.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001134.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001135.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001136.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001137.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001140.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001141.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001142.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001143.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001144.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001145.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001146.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001147.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001148.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001150.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001151.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001153.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001154.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001156.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001157.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001159.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001160.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001161.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001162.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001163.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001164.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001165.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001166.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001168.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001169.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001171.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001172.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001174.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001175.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001177.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001178.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001181.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001182.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001185.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001186.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001187.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001188.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001189.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001192.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001193.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001194.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001195.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001198.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001199.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001200.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001201.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001202.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001203.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001204.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001205.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001206.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001208.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001209.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001211.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001212.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001214.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001215.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001217.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001218.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001219.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001220.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001221.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001222.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001223.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001224.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001225.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001226.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001227.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001228.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001229.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001230.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001231.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001232.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001233.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001234.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001235.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001236.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001237.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001238.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001239.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001240.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001241.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001242.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001244.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001245.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001247.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001248.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001250.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001251.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001253.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001254.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001255.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001256.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001257.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001258.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001259.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001260.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001262.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001263.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001265.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001266.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001268.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001269.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001271.inp --no-xml-output
date

rm -rf $TMPDIR
