#!/bin/sh
#PBS -N H2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2o/pts/inp/main18.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2o/pts/inp/job.0000004642.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004644.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004645.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004647.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004648.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004650.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004651.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004653.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004654.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004657.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004658.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004661.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004662.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004663.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004664.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004665.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004669.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004670.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004671.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004672.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004673.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004674.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004675.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004676.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004677.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004678.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004683.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004684.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004685.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004686.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004687.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004688.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004689.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004691.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004692.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004694.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004695.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004697.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004698.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004700.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004701.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004702.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004703.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004704.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004709.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004710.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004711.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004712.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004713.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004714.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004715.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004717.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004718.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004720.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004721.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004723.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004724.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004726.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004727.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004729.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004730.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004732.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004733.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004735.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004736.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004738.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004739.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004740.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004741.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004742.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004747.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004748.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004749.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004750.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004751.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004752.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004753.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004755.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004756.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004758.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004759.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004761.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004762.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004764.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004765.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004767.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004768.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004770.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004771.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004773.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004774.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004776.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004777.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004779.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004780.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004782.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004783.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004785.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004786.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004788.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004789.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004790.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004791.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004792.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004797.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004798.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004799.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004800.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004801.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004802.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004803.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004805.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004806.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004808.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004809.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004811.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004812.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004814.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004815.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004817.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004818.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004820.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004821.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004823.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004824.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004826.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004827.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004829.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004830.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004832.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004833.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004835.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004836.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004838.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004839.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004841.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004842.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004844.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004845.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004847.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004848.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004850.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004851.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004852.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004853.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004854.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004859.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004860.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004861.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004862.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004863.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004864.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004865.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004867.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004868.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004870.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004871.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004873.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004874.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004876.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004877.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004879.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004880.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004882.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004883.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004885.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004886.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004888.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004889.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004891.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004892.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004894.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004895.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004897.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004898.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004900.inp --no-xml-output
date

rm -rf $TMPDIR
