#!/bin/sh
#PBS -N H2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2o/pts/inp/main6.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2o/pts/inp/job.0000001530.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001531.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001532.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001533.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001534.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001535.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001536.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001537.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001538.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001539.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001540.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001541.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001542.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001543.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001544.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001545.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001546.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001547.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001548.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001549.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001550.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001551.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001552.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001553.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001554.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001555.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001556.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001557.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001558.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001559.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001560.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001561.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001562.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001563.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001564.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001565.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001566.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001567.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001568.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001569.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001570.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001572.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001573.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001575.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001576.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001578.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001579.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001581.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001582.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001583.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001584.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001585.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001586.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001587.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001588.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001589.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001590.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001591.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001592.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001593.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001594.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001595.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001596.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001597.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001598.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001599.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001600.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001601.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001602.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001603.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001604.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001605.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001606.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001607.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001608.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001609.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001610.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001611.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001612.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001613.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001614.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001615.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001616.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001617.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001618.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001619.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001620.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001621.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001622.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001623.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001624.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001625.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001626.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001627.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001628.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001629.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001630.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001631.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001632.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001633.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001634.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001635.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001636.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001637.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001638.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001640.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001641.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001643.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001644.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001646.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001647.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001649.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001650.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001651.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001652.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001653.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001654.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001655.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001656.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001658.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001659.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001661.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001662.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001664.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001665.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001667.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001668.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001670.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001671.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001673.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001674.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001676.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001677.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001679.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001680.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001682.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001683.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001685.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001686.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001688.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001689.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001691.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001692.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001694.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001695.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001697.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001698.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001700.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001701.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001703.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001704.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001707.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001708.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001711.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001712.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001713.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001714.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001715.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001719.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001720.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001721.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001722.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001723.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001724.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001725.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001726.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001727.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001728.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001733.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001734.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001735.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001736.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001737.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001738.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001739.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001741.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001742.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001744.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001745.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001747.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001748.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001750.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001751.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001752.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001753.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001754.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001759.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001760.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001761.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001762.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001763.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001764.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001765.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001767.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001768.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001770.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001771.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001773.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001774.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001776.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001777.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001779.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001780.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001782.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001783.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001785.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001786.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001788.inp --no-xml-output
date

rm -rf $TMPDIR
