#!/bin/sh
#PBS -N H2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2o/pts/inp/main19.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2o/pts/inp/job.0000004901.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004903.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004904.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004906.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004907.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004909.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004910.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004912.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004913.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004915.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004916.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004918.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004919.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004921.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004922.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004924.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004925.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004926.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004927.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004928.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004933.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004934.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004935.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004936.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004937.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004938.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004939.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004941.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004942.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004944.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004945.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004947.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004948.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004950.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004951.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004953.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004954.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004956.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004957.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004959.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004960.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004962.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004963.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004965.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004966.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004968.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004969.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004971.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004972.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004974.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004975.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004977.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004978.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004980.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004981.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004983.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004984.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004986.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004987.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004989.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004990.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004992.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004993.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004995.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004996.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004998.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000004999.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005001.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005002.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005004.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005005.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005007.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005008.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005010.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005011.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005012.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005013.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005014.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005019.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005020.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005021.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005022.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005023.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005026.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005027.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005030.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005031.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005034.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005035.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005038.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005039.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005042.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005043.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005046.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005047.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005050.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005051.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005054.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005055.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005058.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005059.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005062.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005063.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005066.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005067.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005070.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005071.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005074.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005075.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005078.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005079.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000005082.inp --no-xml-output
date

rm -rf $TMPDIR
