#!/bin/sh
#PBS -N H2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2o/pts/inp/main2.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2o/pts/inp/job.0000000495.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000497.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000498.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000500.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000501.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000503.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000504.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000506.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000507.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000509.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000510.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000512.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000513.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000515.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000516.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000518.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000519.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000520.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000521.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000522.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000527.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000528.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000529.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000530.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000531.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000534.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000535.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000538.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000539.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000542.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000543.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000546.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000547.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000550.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000551.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000554.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000555.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000558.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000559.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000560.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000561.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000562.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000563.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000564.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000565.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000566.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000569.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000570.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000571.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000572.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000575.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000576.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000577.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000578.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000579.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000580.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000581.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000584.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000585.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000588.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000589.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000590.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000591.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000592.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000595.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000596.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000597.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000598.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000601.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000602.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000603.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000604.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000605.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000606.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000607.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000608.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000609.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000611.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000612.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000614.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000615.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000617.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000618.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000620.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000621.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000622.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000623.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000624.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000625.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000626.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000627.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000629.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000630.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000632.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000633.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000635.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000636.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000638.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000639.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000642.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000643.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000646.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000647.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000648.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000649.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000650.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000653.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000654.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000655.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000656.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000659.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000660.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000661.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000662.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000663.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000664.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000665.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000666.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000667.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000669.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000670.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000672.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000673.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000675.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000676.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000678.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000679.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000680.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000681.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000682.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000683.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000684.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000685.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000686.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000687.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000688.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000689.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000690.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000691.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000692.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000693.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000694.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000695.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000696.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000697.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000698.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000699.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000700.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000701.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000702.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000703.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000705.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000706.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000708.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000709.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000711.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000712.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000714.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000715.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000716.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000717.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000718.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000719.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000720.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000721.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000723.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000724.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000726.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000727.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000729.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000730.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000732.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000733.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000735.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000736.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000738.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000739.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000741.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000742.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000744.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000745.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000748.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000749.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000752.inp --no-xml-output
date

rm -rf $TMPDIR
