#!/bin/sh
#PBS -N H2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2o/pts/inp/main12.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2o/pts/inp/job.0000003082.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003084.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003085.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003087.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003088.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003090.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003091.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003093.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003094.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003096.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003097.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003099.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003100.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003102.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003103.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003105.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003106.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003107.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003108.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003109.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003114.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003115.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003116.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003117.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003118.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003119.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003120.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003122.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003123.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003125.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003126.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003128.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003129.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003131.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003132.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003134.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003135.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003137.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003138.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003140.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003141.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003143.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003144.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003146.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003147.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003149.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003150.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003152.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003153.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003155.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003156.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003158.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003159.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003161.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003162.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003164.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003165.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003167.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003168.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003170.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003171.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003173.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003174.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003176.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003177.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003179.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003180.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003181.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003182.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003183.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003188.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003189.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003190.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003191.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003192.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003195.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003196.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003199.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003200.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003203.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003204.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003207.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003208.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003211.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003212.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003215.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003216.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003219.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003220.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003223.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003224.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003227.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003228.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003231.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003232.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003235.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003236.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003239.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003240.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003243.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003244.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003245.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003246.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003247.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003248.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003249.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003250.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003251.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003254.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003255.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003256.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003257.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003260.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003261.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003262.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003263.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003264.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003265.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003266.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003269.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003270.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003273.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003274.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003275.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003276.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003277.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003280.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003281.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003282.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003283.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003286.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003287.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003288.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003289.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003290.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003291.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003292.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003293.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003294.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003296.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003297.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003299.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003300.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003302.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003303.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003305.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003306.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003307.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003308.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003309.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003310.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003311.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003312.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003314.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003315.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003317.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003318.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003320.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003321.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003323.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003324.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003327.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003328.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003331.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003332.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003333.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003334.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000003335.inp --no-xml-output
date

rm -rf $TMPDIR
