#!/bin/sh
#PBS -N H2Opts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o tests/cart/h2o/pts/inp/main3.pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb

module load pbspro molpro

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname

molpro -t 1 tests/cart/h2o/pts/inp/job.0000000753.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000754.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000755.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000756.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000759.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000760.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000761.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000762.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000765.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000766.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000767.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000768.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000769.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000770.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000771.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000772.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000773.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000775.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000776.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000778.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000779.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000781.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000782.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000784.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000785.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000786.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000787.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000788.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000789.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000790.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000791.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000792.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000793.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000794.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000795.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000796.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000797.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000798.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000799.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000800.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000801.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000802.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000803.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000804.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000805.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000806.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000807.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000808.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000809.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000811.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000812.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000814.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000815.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000817.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000818.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000820.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000821.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000822.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000823.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000824.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000825.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000826.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000827.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000828.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000829.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000830.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000831.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000832.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000833.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000834.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000835.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000836.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000837.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000838.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000839.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000840.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000841.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000842.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000843.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000844.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000845.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000846.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000847.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000848.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000849.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000850.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000851.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000852.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000853.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000854.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000855.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000856.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000857.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000858.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000859.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000860.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000861.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000863.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000864.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000866.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000867.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000869.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000870.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000872.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000873.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000874.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000875.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000876.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000877.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000878.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000879.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000881.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000882.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000884.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000885.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000887.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000888.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000890.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000891.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000893.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000894.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000896.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000897.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000899.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000900.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000902.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000903.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000905.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000906.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000908.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000909.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000911.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000912.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000914.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000915.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000918.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000919.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000922.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000923.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000924.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000925.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000926.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000930.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000931.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000932.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000933.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000934.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000935.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000936.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000937.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000938.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000939.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000944.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000945.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000946.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000947.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000948.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000949.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000950.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000952.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000953.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000955.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000956.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000958.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000959.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000961.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000962.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000963.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000964.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000965.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000970.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000971.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000972.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000973.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000974.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000975.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000976.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000978.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000979.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000981.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000982.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000984.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000985.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000987.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000988.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000990.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000991.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000993.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000994.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000996.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000997.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000000999.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001000.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001001.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001002.inp --no-xml-output
molpro -t 1 tests/cart/h2o/pts/inp/job.0000001003.inp --no-xml-output
date

rm -rf $TMPDIR
