#!/bin/bash
#SBATCH --job-name={{.Name}}
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH -o {{.Filename}}.pbs.out
#SBATCH --no-requeue
#SBATCH --mem={{.PBSMem}}gb

export LD_LIBRARY_PATH=/home/qc/mopac2016/

hostname
date

{{range $j := .Jobs}}
/home/qc/mopac2016/MOPAC2016.exe {{ $j }}
{{- end }}

date
