#!/bin/sh
#PBS -N pts
#PBS -S /bin/bash
#PBS -j oe
#PBS -o pbs.out
#PBS -W umask=022
#PBS -l walltime=5000:00:00
#PBS -l ncpus=8
#PBS -l mem=64gb

module load intel
module load mvapich2
module load pbspro
export PATH=/usr/local/apps/molpro/2015.1.35/bin:$PATH

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
parallel -j 8 < commands.txt
date

rm -rf $TMPDIR
